### ISSUE TITLE
How do I set the permissions on a newly created directory

### ISSUE THREAD

**Issue by jongravois** [harishanchu/Laravel-FTP#16]
I am using the following to create a new directory to hold uploaded files

```
$path = 'code/LENDA/public/files_loans/' . $crop_year . '_' . $loan->id;
FTP::connection()->makeDir($path);
```

How do I set the permissions on that folder to allow uploads? The docs only talk about setting permission on a file.

Thanks!!!
Jon

**Comment by harishanchu** [comment]
Hi Jongravois,

`permission` method uses the php `ftp_chmod` to change permission of a file. I'm not sure whether `ftp_chmod` support setting permission to a folder, and if it does `permission` method will also work for folders.
