### ISSUE TITLE
Upload file in loop

### ISSUE THREAD

**Issue by mrdaano** [harishanchu/Laravel-FTP#20]
Hello,

I want to upload files with a loop. But I have create a loop:
```php
$i = 1;
foreach(glob(storage_path().'/uploads/'.$opr.'-'.$ver.'-'.$spar.'*') as $picture) {
        echo $picture . "<br>";
	$info = pathinfo($picture);

	FTP::connection()->uploadFile($picture, 'public_html/project/'.$opr.'/images/'.$ver.$spar.'_'.$i.'.'.$info['extension']);
	$i++;
}
```

But it uploads only one file.
And if I debug the file list I see every file.

```php
foreach(glob(storage_path().'/uploads/'.$opr.'-'.$ver.'-'.$spar.'*') as $picture) {
        echo $picture . "<br>";
	$info = pathinfo($picture);
}
```

What can I do?

**Comment by harishanchu** [comment]
Looks like something is wrong with your remote file location.

You can debug the ftp upload by editing the laravel ftp source file in your project in the location: https://github.com/harishanchu/Laravel-FTP/blob/master/src/Anchu/Ftp/Ftp.php#L165
