### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by pickledegg** [harishanchu/Laravel-FTP#25]
How would I inject the FTP class into my own class via type hinting in the constructor? Bearing in mind its using an alias.
If I try the following approach, I get hit with a dependency resolution error.

eg:
```php
use App\Something
...

public function __construct(Something $something)
	{
		$this->something = $something;
	}
```

**Comment by harishanchu** [comment]
`FTP` is an alias to class `Anchu\Ftp\Facades\Ftp`.

The underlying service class for FTP is `Anchu\Ftp\FtpManager'.

So you do this instead of using FTP facade:

```php
use Anchu\Ftp\FtpManager;

public function __construct(FtpManager $ftp)
{
     // do something with $ftp
    $ftp->connection()->getDirListing();
}
```

**Comment by pickledegg** [comment]
I understand why you do would do that, it makes sense, however what am I missing here?
 
**Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Anchu\Ftp\FtpManager**

**Comment by harishanchu** [comment]
It's because $app parameter is not type hinted in the FtpManager class. I have added it now: https://github.com/harishanchu/Laravel-FTP/commit/e0fec2dae79123a7d993afcafa174eb88b45146e . So try again after updating your library, it will work.

**Comment by pickledegg** [comment]
Excellent I just updated and it works perfectly. Thanks very much.

**Comment by harishanchu** [comment]
Anytime :)
