### ISSUE TITLE
Config file naming

### ISSUE THREAD

**Issue by Riesjart** [harishanchu/Laravel-FTP#31]
You closed my pull request, but it was meant to prevent the following error:
php.exe artisan vendor:publish
Can't locate path: C:\xampp\htdocs\project\laravel\vendor\rikless\laravel-ftp\src\Anchu\Ftp/../../config/config.php

**Comment by harishanchu** [comment]
Hi Riesjart,
I found something wrong with this pull request, that is why I closed it. Can I see the changes you made again so that I can explain what was wrong there?

**Comment by Riesjart** [comment]
Hi harishanchu,
Ah now I see, sorry, my bad! Changed my composer.json to your repo now. Thanks.
