### ISSUE TITLE
Test connection

### ISSUE THREAD

**Issue by struyfv** [harishanchu/Laravel-FTP#32]
Hi,

How can I catch if the ftp connection failed? I get the following error: 

ErrorException in Ftp.php line 48:
ftp_login(): Login authentication failed

But I want to get a false or something like that so I can check if it has failed.

**Comment by harishanchu** [comment]
Hi struyfv,

This package throws error on ftp connection failiure, hence before using any other method you better call method `FTP::connection('connection name')` in a try catch statement and make sure ftp connection is success.
