### ISSUE TITLE
Use with Lumen?

### ISSUE THREAD

**Issue by a-harvie** [harishanchu/Laravel-FTP#33]
Hello,

I've got a Lumen app that I need an FTP package for. I installed this one and am running in to an error.

When running `php artisan vendor:publish`, I get the following:
```
PHP Fatal error:  Call to undefined function Anchu\Ftp\config_path() in vendor/anchu/ftp/src/Anchu/Ftp/FtpServiceProvider.php on line 22
```

I tried copying `vendor/anchu/ftp/src/config/config.php` to `config/ftp.php` & filled in the details, but I get the same error when trying to use the package with `FTP::connection()->getDirListing();` (this time with stack trace):

```
PHP Fatal error:  Call to undefined function Anchu\Ftp\config_path() in vendor/anchu/ftp/src/Anchu/Ftp/FtpServiceProvider.php on line 22
PHP Stack trace:
PHP   1. {main}() artisan:0
PHP   2. require() artisan:18
PHP   3. Laravel\Lumen\Application->register() bootstrap/app.php:87
PHP   4. Anchu\Ftp\FtpServiceProvider->boot() vendor/laravel/lumen-framework/src/Application.php:230

Fatal error: Call to undefined function Anchu\Ftp\config_path() in vendor/anchu/ftp/src/Anchu/Ftp/FtpServiceProvider.php on line 22

Call Stack:
    0.0003     225480   1. {main}() artisan:0
    0.0013     232032   2. require('bootstrap/app.php') artisan:18
    0.1031    2440912   3. Laravel\Lumen\Application->register() bootstrap/app.php:87
    0.1049    2456600   4. Anchu\Ftp\FtpServiceProvider->boot() vendor/laravel/lumen-framework/src/Application.php:230
```

I know Lumen is a subset of Laravel's functionality, so there's probably something missing, but it would be great to be able to use your package with it!

**Comment by harishanchu** [comment]
Hi Adam Harvie,

Lumen is a micro-framework based on Laravel. As of that, Lumen does not have all the Laravel featuers (by default). 

This is a Laravel specific package but you can fix this in your project by following the method described in this post: http://laravelista.com/json-web-token-authentication-for-lumen/#improvinglumen
