### ISSUE TITLE
Adding Dynamic FTP Accounts

### ISSUE THREAD

**Issue by furkankadioglu** [harishanchu/Laravel-FTP#35]
Hello!
Thank you for this plugin, i have a little question. I'm trying to add dynamic ftp accounts like this, in routes.php:

> Route::get('/', function () 
> {
>	Config::set('test', array(
           'host'   => 'ip',
           'username' => 'user',
           'port'  => 21,
           'password'   => 'pass.',
           'passive'   => false,
		));
	$listing = FTP::connection('test')->getDirListing();
	return $listing;
});

Giving this result:

Ftp [test] not configured.

How can i use this?

**Comment by puneetverma05** [comment]
Please provide the solution for this issue ?

**Comment by harishanchu** [comment]
It's documented here: https://github.com/harishanchu/Laravel-FTP#configuration

please have a look, Thanks
