### ISSUE TITLE
Why not use Flysystem?

### ISSUE THREAD

**Issue by emilv** [harishanchu/Laravel-FTP#38]
Is there a reason to use this library instead of the built-in Flysystem in Laravel 5? I just added this to my `disks` in filesystems.php:

        'ftp' => [
            'driver' => 'ftp',
            'host' => '...',
            'port' => 21,
            'timeout' => 20,
            'username' => '...',
            'password' => '...',
            'passive' => true,
        ],

And now I can open, read and write files to my heart's content with `Storage::disk('ftp')->...` in the same way as any other filesystem!

Maybe this library is only needed for legacy reasons? Should that be added to the README?

**Comment by harishanchu** [comment]
I don't think you can connect to ftp in laravel 5 just with  its file system feature.

If you meant by using this package: https://github.com/GrahamCampbell/Laravel-Flysystem , then I guess  it's not built in.

**Comment by emilv** [comment]
You're wrong. Laravel ships with a dependency on Flysystem and the core league/flysystem package includes the FTP adapter. The Illuminate [FilesystemManager](https://github.com/laravel/framework/blob/3789a96ec84fdc94685c90eb12e378dedb97411d/src/Illuminate/Filesystem/FilesystemManager.php) handles it out of the box on a bare Laravel install since [March 20015](https://github.com/laravel/framework/commit/648826ce52981353bbfda26e53d546f9d54d101d).

**Comment by harishanchu** [comment]
Yeah, your are right, but methods supported by flysystem adapter may vary from this library. Anyway need to add this to README.

Thanks
