### ISSUE TITLE
Feature Request: UploadFiles

### ISSUE THREAD

**Issue by sineld** [harishanchu/Laravel-FTP#41]
Single file upload works great but a new connection has to be made before every file upload. UploadFiles method work make it great.

**Comment by harishanchu** [comment]
Laravel-FTP makes only one ftp connection per configuration. When you use different methods or single method multiple times with specific ftp configuration library reuses the connection made at the first time. Hence for multiple file upload you may use the single file upload method in a loop.

**Comment by sineld** [comment]
Thanks for informing, cool :)
