### ISSUE TITLE
Limit readFile to x lines 

### ISSUE THREAD

**Issue by doreto** [harishanchu/Laravel-FTP#53]
Would it be good to be able to limit how many lines can be read through files and be sorted from LAST line or FIRST line too

`FTP::connection()->readFile($fileFrom)->limit(30)->DESC`

An example of usage is when you have a large monitoring log on the server and you don't want to read the whole file but only LAST 100 lines.

**Comment by doreto** [comment]
Any thoughts? Is it achievable?

**Comment by harishanchu** [comment]
Hey @doreto , as far as I know php ftp download methods doesn't allow to read n number of lines from remote file. Hence if you want to achieve something like that, you have to download file to local and read required number of lines from there.

Thanks
