### ISSUE TITLE
Ftp [default] not configured.

### ISSUE THREAD

**Issue by yuliantosb** [harishanchu/Laravel-FTP#55]
Hello Mr Haris
I got an error, the error said
`InvalidArgumentException in FtpManager.php line 59: Ftp [default] not configured.`

but I already configure on config/ftp.php

`'default' => 'connection1'`

```
'connections' => array(

        'connection1' => array(
            'host'   => 'localhost',
            'port'  => 14147,
            'username' => 'user1',
            'password'   => 'admin',
            'passive'   => false,
        ),
)
```

in my controller

```
$listing = FTP::connection('default')->getDirListing('ftp://192.168.100.2');
dd($listing);
```

is there something wrong with my code, I wanna access file on my ftp via laravel, is that possible?
thanks for answer, I'm sorry for bad English :)

**Comment by harishanchu** [comment]
Looks like you haven't installed the module properly. Please follow the documentation(https://github.com/harishanchu/Laravel-FTP#installation , https://github.com/harishanchu/Laravel-FTP#configuration) to install and configure the module properly and try again.
