### ISSUE TITLE
Dealing with compressed files and .app extension

### ISSUE THREAD

**Issue by zLegend-210** [harishanchu/Laravel-FTP#57]
Firstly great work! 
This question maybe isn't considered as a bug or problem with your package, I just want help. I have ftp connection and in it there is a .zip file, the compressed file contains a .app file which holds some records for products with their sku's and prices and this .app extension I've never deal with before.

I need to acces that .app file, what should I go for ?

Any help is really appreciated.

**Comment by harishanchu** [comment]
As far as I know you cannot download a specific content inside a zip archive from a ftp server. You have to download the entire archive with ftp commands and extract it in local and read required file in it.

**Comment by zLegend-210** [comment]
@harishanchu I've done something like that, Thank you.
