### ISSUE TITLE
uploadFile error

### ISSUE THREAD

**Issue by lifeagin** [harishanchu/Laravel-FTP#60]
When use uploadFile function，exception like this:
ErrorException: ftp_fput(): php_connect_nonb() failed: Operation now in progress (115)

I was set config passive is true

**Comment by harishanchu** [comment]
This looks like a php ftp module error; Please refer php ftp documentation.

FYI: https://stackoverflow.com/questions/15688331/php-connect-nonb-failed-operation-now-in-progress-115-happens-intermitten
