### ISSUE TITLE
Download a large file to the browser directly

### ISSUE THREAD

**Issue by ozzargueyo** [harishanchu/Laravel-FTP#65]
Hi, nice library. I am trying to download a large file, an PSD file, that is in a remote ftp server that I owned. I'm developing a web app that can download directly to the user's browser. Is there a way to do this, without download it in my server and then to the user?

Thanks!

**Comment by emilv** [comment]
There are these three options:

1. Provide the user with a link to an FTP URL: `ftp://user:password@example.com/path/to/file.psd`
2. Download the file to your server first, then send it to your user. You can use this library's `downloadFile` function followed by [readfile](http://php.net/readfile)
3. Stream the file through your server but send it to the user immediately. You can use this library's `readFile` function, or for example the [Flysystem](http://flysystem.thephpleague.com/api/) streaming functions.

Option 1 leaks the username and password so you have to trust the user  you give the link to.

Option 2 and 3 both requires the file to pass through your server so you have to pay for the bandwidth. Option 3 needs some tinkering to make it actually stream the file. If you do it wrong it will just end up in the output buffer and act exactly like in option 2.

There is no way to stream the file directly to the browser without giving away the username and password.
