### ISSUE TITLE
running php artisan vendor:publish does nothing

### ISSUE THREAD

**Issue by smmx** [harishanchu/Laravel-FTP#67]
Tried in a few 5.5.4 Laravel installs and the package does not show up in the list

**Comment by ahmed-bermawy** [comment]
I have this problem too,
when i try to run `php artisan vendor:publish --tag=config` on Laravel 5.4 nothing happens
also i have added `Anchu\Ftp\FtpServiceProvider::class,` to providers in `config/app.php`

**Comment by VanPhongIT** [comment]
1- Add service provider to providers array on the config/app.php
2- Run php artisan config:cache
3- Run composer update
4- Run php artisan config:cache
5- Run php artisan vendor:publish

**Comment by harishanchu** [comment]
Thank you @VanPhongIT for the explanation.
