### ISSUE TITLE
getDirListing returns false

### ISSUE THREAD

**Issue by phrnndz** [harishanchu/Laravel-FTP#68]
Hello, I was wondering why when I use getDirListing() method it returns me false, however when I use makeDir('directory-name') it does create the directory successfully. Can you help me?

**Comment by milad72t** [comment]
Hi
I had the same issue.
please help

**Comment by harishanchu** [comment]
Here is the source code reference to `getDirListing()` method: https://github.com/harishanchu/Laravel-FTP/blob/v2/src/Anchu/Ftp/Ftp.php#L82 . If it returns false that means some exception was thrown by php `ftp_nlist` method.
