### ISSUE TITLE
PR on v1

### ISSUE THREAD

**Issue by gpaton** [harishanchu/Laravel-FTP#71]
Hello,

I'd like to add a PR to override upload/download mode on v1. Could you please add a v1 branch to allow me that ?

**Comment by gpaton** [comment]
The work is already done on my fork : https://github.com/gpaton/Laravel-FTP/commit/bb1218eda0c055b10b18cf9927d84a1462d5b7ed

**Comment by harishanchu** [comment]
Hi Guillaume,

I have created the v1 branch, now you mad add PR.

**Comment by gpaton** [comment]
Thank you, [PR done](https://github.com/harishanchu/Laravel-FTP/pull/72/)
