### ISSUE TITLE
Laravel 6 Support?

### ISSUE THREAD

**Issue by moe-codes** [harishanchu/Laravel-FTP#75]
Hi All, wondered if there was Laravel 6 support coming?

**Comment by WebKenth** [comment]
> Hi All, wondered if there was Laravel 6 support coming?

In case you need FTP support right now you can simply use the Storage facade :) 

as described in this blog:
https://alexjoffroy.me/blog/how-to-upload-a-local-file-to-a-ftp-with-laravel-1520467200

**Comment by harishanchu** [comment]
Addressed by #76
