### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by ducpvt1804** [harishanchu/Laravel-FTP#77]
i am having problem, pls help me.Thanks

`[2020-10-30 12:48:19] local.ERROR: Array and string offset access syntax with curly braces is deprecated {"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly braces is deprecated at /app/project-name/vendor/anchu/ftp/src/Anchu/Ftp/Ftp.php:125)
[stacktrace]
#0 /app/project-name/vendor/composer/ClassLoader.php(444): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'Array and strin...', '/app/alliance-f...', 125, Array)`

line 125 in src/Anchu/Ftp/Ftp.php: `$item['type'] = $chunks[0]{0} === 'd' ? static::TYPE_DIR : static::TYPE_FILE;`

PHP version: 7.4.3
Laravel version: 5.8.38

**Comment by ducpvt1804** [comment]
@harishanchu pls help me.Thanks

**Comment by ducpvt1804** [comment]
@tomas-novotny pls help me.Thanks

**Comment by tomas-novotny** [comment]
This simple change will fix your problem https://github.com/harishanchu/Laravel-FTP/pull/78/files @ducpvt1804 

But you can always use [Laravel Filesystem Manager](https://laravel.com/docs/5.8/filesystem#driver-prerequisites) which has default support for (S)FTP driver.

```php
$ftp = app('filesystem')->createFtpDriver($config);
// upload
$ftp->put($fileTo, fopen($fileFrom, 'r'));
// download
file_put_contents($fileTo, $ftp->readStream($fileFrom))
```

**Comment by ducpvt1804** [comment]
@tomas-novotny Thank you for your support, hope PR will be incorporated soon.
